
services:

  postgres:
    image: postgres:15
    container_name: chronos-postgres
    environment:
      POSTGRES_DB: chronos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scheduler:
    build: .
    container_name: chronos-scheduler
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped

volumes:
  postgres_data:
