spring.application.name=scheduler
# Server configuration
server.port=8080

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/chronos
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.quartz.job-store-type=jdbc


spring.quartz.properties.org.quartz.scheduler.instanceName=ChronosScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO


